name: drag_and_drop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  arrow_path: ^3.1.0
  bloc: ^9.0.0
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  excel: ^4.0.6
  file_picker: ^10.3.3
  file_saver: ^0.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  path_drawing: ^1.0.1
  super_drag_and_drop: ^0.9.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
